version: '3.4'

# This Guideline will show you how to config env
# https://medium.com/better-programming/using-variables-in-docker-compose-265a604c2006

services:
  app:
    image: resful-demo
    build:
      context: .
      target: production
    env_file: .env
    environment:
      APP_PORT: $APP_PORT
      NODE_ENV: $NODE_ENV
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      RDS_DATABASE: $RDS_DATABASE
      RDS_HOST: db
    ports:
      - 3000:$APP_PORT
    volumes:
      - prod_dep:/prod_dep/node_modules
      - dev_dep:/builder/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn
    command: yarn run start
    networks:
      - nw_demo_rest
    depends_on:
      - db

  db:
    build: ./docker/mysql
    image: restful-db
    env_file: .env
    container_name: db

    environment:
      # using db root account
      MYSQL_ROOT_PASSWORD: $RDS_PASSWORD 
      MYSQL_DATABASE: $RDS_DATABASE
      # MYSQL_USER: $RDS_USERNAME
      # MYSQL_PASSWORD: $RDS_PASSWORD
    ports:
      - 3306:3306
    networks:
      - nw_demo_rest
    # volumes:
    #   - ./mysql:/var/lib/mysql

networks:
  nw_demo_rest:
    driver: bridge

volumes:
  yarn_cache:
  dev_dep:
  prod_dep:
